config/routes.rb
Rails.application.routes.draw do

  get 'carts/create'
  get 'orders/create'
  match "/404", :to => 'errors#not_found', :via => :all
  match "/500", :to => 'errors#internal_server_error', :via => :all
  get 'dj_set_validates/valid'
  get 'dj_sets/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :events do
    collection do
      post :import
      get :calendar
    end
  end
  root 'home#index_change'
  get 'home/index_change', to: 'home#index_change'

  get 'home/private'
  resources :contacts, only: [:index, :new, :create]
  resources :realreleases
  resources :artists
  resources :djsets
  resources :tracks
  resources :articles
  resources :stocks

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/article.rb
class Article < ApplicationRecord
  #validates :title, :content, presence: true
  belongs_to :user
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :realreleases, dependent: :destroy
  has_many :djsets, :inverse_of => :artist, dependent: :destroy
  has_many :tracks, through: :realreleases, dependent: :destroy
  accepts_nested_attributes_for :realreleases
  accepts_nested_attributes_for :djsets
  validates :name, presence: true
  has_one_attached :image
  
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orders
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate =>true

  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "jonathan.mete101514@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/djset.rb
class Djset < ApplicationRecord
  belongs_to :artist, :inverse_of => :djsets
  validates_presence_of :artist
  validates :club, :start, :emailforrequest, presence: true

end

app/models/event.rb
class Event < ApplicationRecord
  include ::ComptabilityConcern
  require 'csv'
  scope :last_event, -> { where(id:Event.last.id) }
  validates :name, presence: true
  validates :charge_communication, presence: true
  validates :charge_others, presence: true
  validates :total_charge_dj, presence: true
  validates :revenue_figure, presence: true, allow_nil: true

  def headers
    {
      :subject => "Contact Form Test encore",
      :to => "jonathan.mete@hotmail.fr",
      :from => %("michou")
    }
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Event.create! row.to_hash
    end
  end

  def start_time
      self.start
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :realrelease
  belongs_to :cart
end

app/models/realrelease.rb
class Realrelease < ApplicationRecord
  belongs_to :artist
  has_one :stock
  has_many :tracks, inverse_of: :realrelease, dependent: :destroy
  accepts_nested_attributes_for :tracks
  has_one_attached :image
  validates_presence_of :artist
  validates :name, presence: true
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :realrelease
  validates_presence_of :realrelease
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :realrelease, inverse_of: :tracks
  validates_presence_of :realrelease
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  require 'open-uri'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise  :omniauthable, omniauth_providers: [:facebook]
  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      # assuming the user model has a name
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
       user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
protect_from_forgery

  def create
  @artist = Artist.create(artist_params)
      respond_to :js
  end

  def new
    @artist = Artist.new(params[:artist])
    @djset = Djset.new(params[:djset])
  end

  def index
    respond_to do |format|
      format.html do
        @artists = Artist.all
      end
      format.json do
        render json: {artists_count: @artists.count}
        puts @artists.count
      end
    end
  end

  def edit
     @artist = Artist.find(params[:id])
  end

  def show
     @artist = Artist.find(params[:id])
     @artist_djset = @artist.djsets
  end

  def update
    @artist = Artist.find(params[:id])
    @djsets_count_before = @artist.djsets.count
    if @artist.update_attributes(artist_params)
      flash.now[:notice] = "#{@artist.name.upcase} was successfully updated ! "

      if @djsets_count_before < @artist.djsets.count
        puts '_________________________________________________________________grandit'
        ArtistMailer.with(artist: @artist).welcome_email.deliver_later
        puts '___________________________________________________envoi du mail'
      else
        puts "_________________________________________________________________update didn't concern dj set"
      end
      render :show
    else
      flash.now[:alert] = "All the field must be filled for the artist"
      render :edit
    end
  end

  def number_of_djset
    @artist = Artist.find(params[:id])
    @djset_number = @artist.djsets.count
    puts "___________________________________________________#{@djset_number} djsets number for #{@artist.name}"
  end

  def destroy
    @artist = Artist.find(params[:id])
    ArtistDestroyWorkerWorker.perform_async
    respond_to do |format|
     format.js
     format.html { redirect_to artists_url, notice: 'artist was successfully destroyed.' }
     format.json { head :no_content }
  end
end

  def calendar
    @artist = Artist.find(params[:id])
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :image, realreleases_attributes: [:id, :name, :image, :production_year, :_destroy], djsets_attributes: [:id, :start, :club, :confirmdjset, :_destroy, :_create])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dj_sets_helper.rb
module DjSetsHelper
end

app/helpers/djs_helper.rb
module DjsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/views/artists/_artist.html.erb
<tr id="tr-column" >
  <td class="td-row absolute2"><p><%= link_to artist.name.upcase, artist, id:"td-artist-name" %></p></td>
  <td class="td-row round"><%  if artist.image.attached?  %>
  <%= image_tag artist.image, style:('width:100%;height:auto;'),class:'background-artist-image' %>
  <% else %>
  <% end %>

  </td>
  <%-# commented line -%>

  <!-- Reveal using custom parameters. -->
</tr>

app/views/artists/_calendar.html.erb
<div class="block3">
  <div class="calendar">

  </div>
</div>

app/views/artists/_form.html.erb
<div class="new-artist-form">
  <%= form_for @artist, remote: true  do |f| %>
  <p>Name</p>
  <p><%= f.text_field :name, placeholder:"Name of artist...", id:"text-field-new-artist"%><br></p>
  <%= f.submit class:"file-field-new-artist" %>
  <% end %>
</div>

app/views/artists/create.js.erb
$('.new-artist-form').fadeOut(900, function(){ $(this).remove();});
$('.ajax-add-new-artist').fadeIn(900);
$('table#artists tbody').append("<%= j render @artist %>");

app/views/artists/destroy.js.erb
$('.destroy-artist').bind('ajax:success', function() {
	$(this).closest('tr').fadeOut();
});

app/views/artists/edit.html.erb
<div class="block margin-top">
  <div class="just-column">

    <div class="bottom small-row-artist">
    <p class="artist-name bottom">  <%= link_to @artist.name.upcase, artist_path, style:'color:#8e8e8e;'%> </p> <!--<%= image_tag 'settings.png', style:"margin-left:30px;margin-bottom:-10px;width:50px;height:50px;"%></p>-->
    </div>

    <div class="just-column">

      <!-- EDIT ARTIST-->
      <%= form_for @artist do |f| %>
      <div class="just-column bottom border-bot">
        <p style="margin-bottom:20px;">ADD A PROFIL PICTURE</p>
        <p><%= f.file_field :image, class:"file-field-new-artist", class:"none-border" %></p>
        <p><%= image_submit_tag 'save.png', class:"save", style:'margin-top:23px;'%></p>
        <p> <br></p>
      </div>
      <% end %>
      <!-- EDIT ARTIST END-->


      <!-- CREATE DJ SET-->
  
      <!-- DJ SET END-->

      <!-- CREATE RELEASE-->
      <%= form_for @artist do |f| %>
      <%= f.fields_for :realreleases, Realrelease.new do |realrelease_form| %>
      <div class="just-column bottom-border bottom">
        <p> <br></p>
        <div class="just-row">
          <p  style="margin-bottom:20px;">ADD A RELEASE FOR </p><p class='info'><%= @artist.name.upcase %></p>
        </div>
        <p style='margin-bottom:10px;'>Name</p> <br> <p><%= realrelease_form.text_field :name, :placeholder => "Name of the release", class:"submit", style:'margin-bottom:10px;' %></p>
        <p style='margin-bottom:10px;'>Year</p>
        <br>
        <p><%= realrelease_form.text_field :production_year,:placeholder =>  "Year of the production", class:"submit", style:'margin-bottom:10px;' %></p>
        <p style='margin-bottom:10px;'>Cover</p>
        <div class="block2">
          <p style='margin-bottom:10px;'><%= realrelease_form.file_field :image %></p>
          <% end %>
        </div>
        <p><%= image_submit_tag 'save.png', class:"save"%></p>
      </div>
      <% end %>
      <!-- RELEASE END-->

    </div>
  </div>
</div>

app/views/artists/index.html.erb
<div class="artist-content ">
  <div class="new-link">
    <div class="ajax-add-new-artist">
      <%= link_to new_artist_path, id:'ajax-add-new-artist', remote: true do %>
      <div class="small-row">

      <p ><%= image_tag "add2.png", :style => "width:80%;margin-top:-4px;" %></p><p id="ajax-add-new-artist" > ADD NEW ARTIST</p>
    </div>
      <%end%>
    </div>
  </div>
  <div class="artist-list-content">
    <table id="artists">
      <tbody>
      <%= render partial: 'artist', collection: @artists %>
      </tbody>
    </table>
  </div>
</div>
<div id="app-container">
</div>
<%= javascript_pack_tag 'application2' %>

app/views/artists/new.html.erb
<div class="new-artist-form">
  <%= form_for @artist do |f| %>
    <p>Name</p>
    <p><%= f.text_field :name, placeholder:"Name of artist...", id:"text-field-new-artist"%><br></p>
    <p>Image</p>
    <p><%= f.file_field :image, class:"file-field-new-artist" %><br></p>
    <%= f.submit class:"file-field-new-artist" %>
  <% end %>
</div>

app/views/artists/new.js.erb
$('.new-link').append("<%= j render 'form'%>");
$('.ajax-add-new-artist').hide(1800);

app/views/artists/show.html.erb
<div class="block">
  <div class="just-column large">

    <!-- First block -->
    <div class="small-row-artist space-between-simple">
      <p class="artist-name margin-bottom"><%=@artist.name.upcase%></p>
      <div class="just-column border-left block-width">
        <br>
        <%  if @artist.image.attached?  %>
          <%= image_tag @artist.image,class:'background-artist-image', style:"width:50px;margin-top:-20px;" %>
        <%end %>
      </div>
      <!-- If Admin -->
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <div class="just-row space-between-simple">
            <%= link_to image_tag('edit.png'), edit_artist_path(@artist),  class:'background-grey box-shadow3', style:'height:35px'%>
            <%= link_to image_tag('delete2.png'), artist_path(@artist), method: :delete, data: { confirm: 'Are you sure to delete this artist ? Every related stuff, releases, sets, and tracks associate will be erased as well...' },  class:'background-grey box-shadow3', style:'height:35px;' %>
          </div>
        <%end%>
      <%end%>
      <!-- If Admin END -->
    </div>
    <!-- First block END -->


    <!-- Block2 -->
    <div class="block2 margin-bottom height-max bred">
      <div class="just-column ">
        <p class="little-title small-margin-bottom">Realeases</p>
        <div class="just-column-inside border-radius  width100 overflow-vertical ">
          <% for realrelease in @artist.realreleases %>
          <div class="just-column hover-line ">
            <%= link_to realrelease.name, realrelease%>
            <%=  realrelease.production_year%>
            <% if realrelease.image.attached?  %>
            <%= image_tag realrelease.image, style:('width:40px;height:auto;')%>
            <%end%>
            <p><br></p>
          </div>
          <% end %>
        </div>
      </div>

      <div class="just-column border-left ">
        <p class="little-title small-margin-bottom">Next date</p>
        <div class="just-column-inside border-radius  width300 overflow-vertical ">
          <% for dj_set in @artist.djsets %>
          <div class="just-column hover-line ">
            <!-- If user connected and admin show the status of all date-->
            <% if user_signed_in? %>
              <%if  current_user.admin?%>
                <p>The <%=  dj_set.start.strftime("%Y-%m-%d")%> At <%=  dj_set.start.strftime("%I:%M%p")%> at <%=  dj_set.club%></p>
                <% if dj_set.confirmdjset %>
                  <%= link_to djsets_path do %>  <p class="date-confirmed">Date Confirmed :)</p><%end%>
                <% elsif dj_set.confirmdjset.nil?  %>
                  <%= link_to djsets_path do %><p class="pending">Pending...</p><%end%>
                <% else   %>
                  <%= link_to djsets_path do %><p class="date-rejected">date rejected :(</p><%end%>
                <%end%>
              <%else%>
              <%end%>
            <%else%>
            <%end%>
            <!-- If user connected and admin show the status of all date END-->

            <!-- If just date confirmed, then show it-->
            <% if dj_set.confirmdjset %>
              <p>The <%=  dj_set.start.strftime("%Y-%m-%d")%> At <%=  dj_set.start.strftime("%I:%M%p")%> at <%=  dj_set.club%></p>
            <%else%>
            <%end%>
            <!-- If just date confirmed, then show it END-->

          </div>
          <% end %>
        </div>
      </div>
    </div>
    <!-- Block 2 END -->




  </div>
</div>