config/routes.rb
Rails.application.routes.draw do

  get 'carts/create'
  get 'orders/create'
  match "/404", :to => 'errors#not_found', :via => :all
  match "/500", :to => 'errors#internal_server_error', :via => :all
  get 'dj_set_validates/valid'
  get 'dj_sets/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :events do
    collection do
      post :import
      get :calendar
    end
  end
  root 'home#index_change'
  get 'home/index_change', to: 'home#index_change'

  get 'home/private'
  resources :contacts, only: [:index, :new, :create]
  resources :realreleases
  resources :artists
  resources :djsets
  resources :tracks
  resources :articles
  resources :stocks

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/article.rb
class Article < ApplicationRecord
  #validates :title, :content, presence: true
  belongs_to :user
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :realreleases, dependent: :destroy
  has_many :djsets, :inverse_of => :artist, dependent: :destroy
  has_many :tracks, through: :realreleases, dependent: :destroy
  accepts_nested_attributes_for :realreleases
  accepts_nested_attributes_for :djsets
  validates :name, presence: true
  has_one_attached :image
  
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orders
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate =>true

  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "jonathan.mete101514@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/djset.rb
class Djset < ApplicationRecord
  belongs_to :artist, :inverse_of => :djsets
  validates_presence_of :artist
  validates :club, :start, :emailforrequest, presence: true

end

app/models/event.rb
class Event < ApplicationRecord
  include ::ComptabilityConcern
  require 'csv'
  scope :last_event, -> { where(id:Event.last.id) }
  validates :name, presence: true
  validates :charge_communication, presence: true
  validates :charge_others, presence: true
  validates :total_charge_dj, presence: true
  validates :revenue_figure, presence: true, allow_nil: true

  def headers
    {
      :subject => "Contact Form Test encore",
      :to => "jonathan.mete@hotmail.fr",
      :from => %("michou")
    }
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Event.create! row.to_hash
    end
  end

  def start_time
      self.start
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :realrelease
  belongs_to :cart
end

app/models/realrelease.rb
class Realrelease < ApplicationRecord
  belongs_to :artist
  has_one :stock
  has_many :tracks, inverse_of: :realrelease, dependent: :destroy
  accepts_nested_attributes_for :tracks
  has_one_attached :image
  validates_presence_of :artist
  validates :name, presence: true
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :realrelease
  validates_presence_of :realrelease
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :realrelease, inverse_of: :tracks
  validates_presence_of :realrelease
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  require 'open-uri'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise  :omniauthable, omniauth_providers: [:facebook]
  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      # assuming the user model has a name
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
       user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def create
  article = Article.create(article_params)
    if article.save
      respond_to do |format|
        format.html do
          flash[:success] = "Article created"
          redirect_to articles_path
        end
        format.json do
          render json: article
        end
      end

    else
      flash[:error] = "failed niga"
      redirect_to articles_path
    end
  end

  def new
    @article = Article.new(params[:article])
      @articles = Article.all
  end

  def index
    @articles = Article.all
    respond_to do |format|
      format.html do
      end
      format.json do
        render json: @articles
      end
    end
  end

  def edit
     @article = Article.find(params[:id])
  end

  def show
     @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update_attributes(article_params)
    flash[:notice] = "#{@article.title} was successfully updated."
    redirect_to articles_path
  end

  def destroy
    Article.find(params[:id]).destroy
     flash[:success] = "article deleted"
     redirect_to articles_url
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dj_sets_helper.rb
module DjSetsHelper
end

app/helpers/djs_helper.rb
module DjsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/views/articles/_article.html.erb
<div class="article-uniq">
  <h1><%= article.title %></h1>
  <p id="date">Publier le <%= article.created_at%></p>
  <p id=content-article><%= article.content %></p>
  <% if user_signed_in? %>
    <% if current_user.admin? %>
      <div class="litle-row">
        <p id="edit-and-show"><%= link_to 'Edit', edit_article_path(article), class:"icone-in-table" %></p>
        <p id="edit-and-show">  <%= link_to 'Show', article, class:"icone-in-table" %></p>
        <p id="bin"><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class:"icone-in-table" %></p>
      </div>
    <% else %>
    <%end%>
  <%else%>
  <%end%>
</div>

<% if user_signed_in? %>
  <% if current_user.admin? %>
  <div class="new-articles">
  <p id="new-one">  <%= link_to 'New Article', new_article_path %></p>
  </div>
  <% else %>
  <%end%>
<%else%>
<%end%>

app/views/articles/_index.html.erb
<%=flash[:notice]%>
<table class="table">
    <thead class="titre">
      <tr class="elementoftitle">
        <th class="element-title"><p>Title</p><p>:</p></th>
        <th class="element-title"><p>Content</p><p>:</p></th>

      </tr>

  </thead>


  <tbody class="content">
    <% @articles.each do |article| %>
      <tr class="elementofcontent">
        <td class="element"><%= article.title %></td>
        <td class="element"><%= article.content %></td>
        <td class="element"><%= link_to 'Edit', edit_article_path(article), class:"icone-in-table" %></td>
        <td class="element"><%= link_to 'Show', article, class:"icone-in-table" %></td>
        <td class="element" id="icone-in-table"><%= link_to image_tag('delete.png', size: "32x32"), article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class:"icone-in-table" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_index_test.html.erb
<%=flash[:notice]%>
<table class="table">
    <thead class="titre">
      <tr class="elementoftitle">
        <th class="element-title"><p>Title</p><p>:</p></th>
        <th class="element-title"><p>Content</p><p>:</p></th>

      </tr>

  </thead>


  <tbody class="content">
    <% @articles.each do |article| %>
      <tr class="elementofcontent">
        <td class="element"><%= article.title %></td>
        <td class="element"><%= article.content %></td>
        <td class="element"><%= link_to 'Edit', edit_article_path(article), class:"icone-in-table" %></td>
        <td class="element"><%= link_to 'Show', article, class:"icone-in-table" %></td>
        <td class="element" id="icone-in-table"><%= link_to image_tag('delete.png', size: "32x32"), article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class:"icone-in-table" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<div class="container-edit">
  <div class="carreblanc">
    <div class="form">
      <%= form_for @article do |f| %>
        <div class="row-edit">
          <p>Title</p>
          <p>
          <%= f.text_field :title %><br>
          </p>
        </div>
        <div class="row-edit">
          <p>Content</p>
          <p>
          <%= f.text_field :content
           %><br>
          </p>
        </div>
      <%= f.submit %>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="articles">
  <%= render partial: 'article', collection: @articles %>


</div>
<div id="app-container">

</div>
<%= javascript_pack_tag 'application' %>

app/views/articles/new.html.erb
<div class="articles">

<h1>New article</h1>
<%= form_for @article do |f| %>
  <p>  Title<br>
  <%= f.text_field :title, placeholder:"Titre de l'article...", class:'field' %>
  </p>
  <p>
  Content<br>

      <%= f.text_field :content, placeholder:"Contenu de l'article...", class:'field-content'%>

    </p>
  <p>
    <%= f.submit 'Create Article', class:"submit" %>
  </p>
<% end %>
</div>