config/routes.rb
Rails.application.routes.draw do

  get 'carts/create'
  get 'orders/create'
  match "/404", :to => 'errors#not_found', :via => :all
  match "/500", :to => 'errors#internal_server_error', :via => :all
  get 'dj_set_validates/valid'
  get 'dj_sets/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :events do
    collection do
      post :import
      get :calendar
    end
  end
  root 'home#index_change'
  get 'home/index_change', to: 'home#index_change'

  get 'home/private'
  resources :contacts, only: [:index, :new, :create]
  resources :realreleases
  resources :artists
  resources :djsets
  resources :tracks
  resources :articles
  resources :stocks

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/article.rb
class Article < ApplicationRecord
  #validates :title, :content, presence: true
  belongs_to :user
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :realreleases, dependent: :destroy
  has_many :djsets, :inverse_of => :artist, dependent: :destroy
  has_many :tracks, through: :realreleases, dependent: :destroy
  accepts_nested_attributes_for :realreleases
  accepts_nested_attributes_for :djsets
  validates :name, presence: true
  has_one_attached :image
  
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orders
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate =>true

  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "jonathan.mete101514@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/djset.rb
class Djset < ApplicationRecord
  belongs_to :artist, :inverse_of => :djsets
  validates_presence_of :artist
  validates :club, :start, :emailforrequest, presence: true

end

app/models/event.rb
class Event < ApplicationRecord
  include ::ComptabilityConcern
  require 'csv'
  scope :last_event, -> { where(id:Event.last.id) }
  validates :name, presence: true
  validates :charge_communication, presence: true
  validates :charge_others, presence: true
  validates :total_charge_dj, presence: true
  validates :revenue_figure, presence: true, allow_nil: true

  def headers
    {
      :subject => "Contact Form Test encore",
      :to => "jonathan.mete@hotmail.fr",
      :from => %("michou")
    }
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Event.create! row.to_hash
    end
  end

  def start_time
      self.start
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :realrelease
  belongs_to :cart
end

app/models/realrelease.rb
class Realrelease < ApplicationRecord
  belongs_to :artist
  has_one :stock
  has_many :tracks, inverse_of: :realrelease, dependent: :destroy
  accepts_nested_attributes_for :tracks
  has_one_attached :image
  validates_presence_of :artist
  validates :name, presence: true
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :realrelease
  validates_presence_of :realrelease
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :realrelease, inverse_of: :tracks
  validates_presence_of :realrelease
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  require 'open-uri'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise  :omniauthable, omniauth_providers: [:facebook]
  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      # assuming the user model has a name
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
       user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def create
    @stock = Stock.create(stock_params)
    if @stock.save
      flash[:success] = "bingo "
      redirect_to stocks_path
    else
      flash[:error] = "failed "
      redirect_to stocks_path
    end
  end

  def new
    @stock = Stock.new(params[:Stock])
    @stocks = Stock.all
  end

  def index
    @stocks = Stock.all
  end

  def edit
    @stock = Stock.find(params[:id])
  end

  def show
    @stock = Stock.find(params[:id])
  end

  def update
    @stock = Stock.find(params[:id])
    @stock.update_attributes(stock_params)
    flash[:notice] = "The stock of #{@stock.realrelease.name} was successfully updated."
    redirect_to stocks_path
  end

  def destroy
    Stock.find(params[:id]).destroy
     flash[:success] = "Stock deleted"
     redirect_to stocks_url
  end

  private

  def stock_params
    params.require(:stock).permit(:quantity, :price)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dj_sets_helper.rb
module DjSetsHelper
end

app/helpers/djs_helper.rb
module DjsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/views/stocks/create.html.erb
<h1>Stock#create</h1>
<p>Find me in app/views/stock/create.html.erb</p>

app/views/stocks/destroy.html.erb
<h1>Stock#destroy</h1>
<p>Find me in app/views/stock/destroy.html.erb</p>

app/views/stocks/edit.html.erb
<div class="container-edit">
  <div class="carreblanc">
    <div class="form">
      <%= form_for @stock do |f| %>
      <div class="row-edit">
        <p>@stock.realrelease.name</p>
      </div>

        <div class="row-edit">
          <p>quantity</p>
          <p>
          <%= f.number_field :quantity %><br>
          </p>
        </div>
        <div class="row-edit">
          <p>Price</p>
          <p>
          <%= f.number_field :price
           %><br>
          </p>
        </div>
      <%= f.submit %>
    </div>
    <% end %>
  </div>
</div>

app/views/stocks/index.html.erb
<h1 style="margin-top:60px">STOCK</h1>

<div style="margin-top:30px;">

  <div class="just-row tableau3">
    <p></p>
    <p>name</p>
    <p>quantity</p>
    <p>price</p>
  </div>

  <%@stocks.each do |s| %>
    <div class="just-row tableau3">
      <p><%= link_to "EDIT", edit_stock_path(s)%></p>
      <p><%=s.realrelease.name %></p>
      <p><%=s.price %></p>
      <p><%=s.quantity %></p>
    </div>
  <%end %>

</div>

app/views/stocks/new.html.erb
<div class="new-artist-form">
  <%= form_for @stock do |f| %>
    <p>price</p>
    <p><%= f.number_field :price, placeholder:"price of realreleaseease...", id:"text-field-new-artist"%><br></p>
    <p>quantity</p>
    <p><%= f.number_field :quantity, class:"file-field-new-artist" %><br></p>
    <%= f.submit class:"file-field-new-artist" %>
  <% end %>
</div>

app/views/stocks/update.html.erb
<h1>Stock#update</h1>
<p>Find me in app/views/stock/update.html.erb</p>