config/routes.rb
Rails.application.routes.draw do

  get 'carts/create'
  get 'orders/create'
  match "/404", :to => 'errors#not_found', :via => :all
  match "/500", :to => 'errors#internal_server_error', :via => :all
  get 'dj_set_validates/valid'
  get 'dj_sets/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :events do
    collection do
      post :import
      get :calendar
    end
  end
  root 'home#index_change'
  get 'home/index_change', to: 'home#index_change'

  get 'home/private'
  resources :contacts, only: [:index, :new, :create]
  resources :realreleases
  resources :artists
  resources :djsets
  resources :tracks
  resources :articles
  resources :stocks

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/article.rb
class Article < ApplicationRecord
  #validates :title, :content, presence: true
  belongs_to :user
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :realreleases, dependent: :destroy
  has_many :djsets, :inverse_of => :artist, dependent: :destroy
  has_many :tracks, through: :realreleases, dependent: :destroy
  accepts_nested_attributes_for :realreleases
  accepts_nested_attributes_for :djsets
  validates :name, presence: true
  has_one_attached :image
  
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orders
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate =>true

  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "jonathan.mete101514@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/djset.rb
class Djset < ApplicationRecord
  belongs_to :artist, :inverse_of => :djsets
  validates_presence_of :artist
  validates :club, :start, :emailforrequest, presence: true

end

app/models/event.rb
class Event < ApplicationRecord
  include ::ComptabilityConcern
  require 'csv'
  scope :last_event, -> { where(id:Event.last.id) }
  validates :name, presence: true
  validates :charge_communication, presence: true
  validates :charge_others, presence: true
  validates :total_charge_dj, presence: true
  validates :revenue_figure, presence: true, allow_nil: true

  def headers
    {
      :subject => "Contact Form Test encore",
      :to => "jonathan.mete@hotmail.fr",
      :from => %("michou")
    }
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Event.create! row.to_hash
    end
  end

  def start_time
      self.start
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :realrelease
  belongs_to :cart
end

app/models/realrelease.rb
class Realrelease < ApplicationRecord
  belongs_to :artist
  has_one :stock
  has_many :tracks, inverse_of: :realrelease, dependent: :destroy
  accepts_nested_attributes_for :tracks
  has_one_attached :image
  validates_presence_of :artist
  validates :name, presence: true
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :realrelease
  validates_presence_of :realrelease
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :realrelease, inverse_of: :tracks
  validates_presence_of :realrelease
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  require 'open-uri'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise  :omniauthable, omniauth_providers: [:facebook]
  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      # assuming the user model has a name
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
       user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/events_controller.rb
  # encoding: utf-8
 class EventsController < ApplicationController
 skip_before_action :verify_authenticity_token
 before_action :set_event, only: %i[destroy edit show update]

   def index
     @events = Event.all
    
   end

   def new
     @event = Event.new(params[:artist])
   end

   def create
     @event = Event.create(event_params)
     @event.save
     redirect_to events_path
   end

   def calendar
     @events = Event.all
   end

   def import
     @event = Event.import(params[:file])
     redirect_to events_path
   end

   def edit; end

   def show; end

   def update
    @event.update_attributes(event_params)
    flash[:notice] = "#{@event.name} was successfully updated."
    redirect_to events_path
   end

   def destroy
     @event.destroy
     respond_to do |format|
      format.js
      format.html { redirect_to artists_url, notice: 'artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


   private

     def event_params
       params.require(:event).permit(:revenue_figure, :total_charge_dj, :charge_flyers,
                                    :charge_others, :number_of_dj, :line_up, :place, :name, :start)
     end

     def set_event
      @event = Event.find(params[:id])
    end
 end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dj_sets_helper.rb
module DjSetsHelper
end

app/helpers/djs_helper.rb
module DjsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/views/events/_event.html.erb
  <tr class="elementofcontent">
    <td class="element scroll-x"><%= event.name %></td>
    <td class="element"> <%= event.place %></td>
    <td class="element"> <%= event.start %></td>
    <td class="element scroll-x"><%= event.line_up %></td>
    <td class="element"><%= event.number_of_dj %></td>

    <% if  event.revenue_figure.nil?  %>
    <td class="element avenir">à venir </td>
    <% else %>
    <td class="element"><%= event.revenue_figure %>$</td>
    <%end%>

    <% if  event.total_charge_dj.nil?  %>
    <td class="element avenir">à venir </td>
    <% else %>
    <td class="element"><%= event.total_charge_dj %>$</td>
    <%end%>

    <% if  event.charge_communication.nil?  %>
    <td class="element avenir">à venir </td>
    <% else %>
    <td class="element"><%= event.charge_communication %>$</td>
    <%end%>

    <% if  event.charge_others.nil?  %>
    <td class="element avenir">à venir </td>
    <% else %>
    <td class="element"><%= event.charge_others %>$</td>
    <%end%>

    <% if  event.charge_others.nil?  %>
    <td class="element avenir">à venir </td>
    <% else %>
    <td class="element calcul"><%= event.benefits %>$</td>
    <%end%>

    <td class="element">
      <% if event.positiv_benefits_rate %>
      <p class = "positiv"><%= event.benefits_rate %>%</p>
      <% else %>
      <p class="negativ"><%= event.benefits_rate %>%</p>
      <%end%>
    </td>

    <td class="element">
      <% if event.positiv_return_rate %>
      <p class = "positiv"><%= event.return_rate %>%</p>
      <% else %>
      <p class="negativ"><%= event.return_rate %>%</p>
      <%end%>
    </td>

    <td class="element" id="icone-in-table"><%= link_to image_tag('edit.png', size: "32x32"), edit_event_path(event), class:"icone-in-table icon-button" %></td>
    <td class="element" id="icone-in-table"><%= link_to image_tag('eye.png', size: "32x32"), event, class:"icone-in-table icon-button" %></td>
    <td class="element" id="icone-in-table"><%= link_to image_tag('delete2.png', size: "32x32"), event_path(event), method: :delete, data: { confirm: 'Are you sure?' }, class:"icone-in-table icon-button", remote: true %></td>
  </tr>

app/views/events/_form.html.erb
<div class="form-import-csv-events">

  <%= form_tag import_events_path, multipart: true, remote:true do%>
  <div class="just-row">
    <p>Choose your event : </p>
    <div id="submit-column">
      <div class="just-row"><p><%= file_field_tag :file %></p></div>
      <div class="just-row pink">
      <p class="save-button"><%= image_submit_tag("add.png", width:"35px") %></p>
      <p style="font-size:12px;">Ajouter le fichier CSV</p>
      </div>
    </div>
  </div>
  <%end%>
</div>

app/views/events/calendar.html.erb
<div class="calendar">

<%= month_calendar events: @events do |date, events| %>
  <%= date %>
  <% events.each do |event| %>
  <%=link_to event_path(event.id) do %>
  <p><%=  event.name.upcase %></p>
  At
  <p> <div class="">

  <%= event.place.upcase%></div></p>
  <%end%>


  <% end%>

<% end %>
<%if user_signed_in? %>
<% if current_user.admin? %>
<%= link_to "Add event", new_event_path %>
<%else%>
<%end%>
<%else%>
<%end%>
</div>

app/views/events/destroy.js.erb
$('.icone-in-table').bind('ajax:success', function() {
	$(this).closest('tr').fadeOut();
});

app/views/events/edit.html.erb
<div class="container-edit">
  <div class="carreblanc">
    <div class="form">
      <%= form_for @event do |f| %>
        <div class="row-edit">
          <p>Name</p>
          <p>
          <%= f.text_field :name %><br>
          </p>
        </div>
        <div class="row-edit">
          <p>Place</p>
          <p>
          <%= f.text_field :place
           %><br>
          </p>
        </div>
        <div class="row-edit">
          <p>Line up</p>
          <p>
          <%= f.text_field :line_up %><br>
          </p>
        </div>
        <div class="row-edit">
          <p>Number of dj</p>
          <p>
          <%= f.number_field :number_of_dj %><br>
          </p>
        </div>
        <div class="row-edit">
          <p>Revenue Figure </p>
          <p>
          <%= f.number_field :revenue_figure %><br>
          </p>
        </div>
        <div class="row-edit">
          <p>Total Charge Dj</p>
          <p>
          <%= f.number_field :total_charge_dj %><br>
          </p>
        </div>
        <div class="row-edit">
          <p>Charge Communication</p>
          <p>
          <%= f.number_field :charge_communication %><br>
          </p>
          </div>
        <div class="row-edit">
          <p>Charge Others</p>
          <p>
          <%= f.number_field :charge_others %><br>
          </p>
        </div>
      <%= f.submit %>
    </div>
    <% end %>
  </div>
</div>

app/views/events/import.js.erb
$('table#table tbody').append("<%= j render @event %>", dataType: 'js');
$('.ajax-add-new-event').fadeIn(900);

app/views/events/index.html.erb
<%=flash[:notice]%>
<table class="table">
    <thead class="titre">
      <tr class="elementoftitle">
        <th class="element-title"><p>Name</p></th>
        <th class="element-title"><p>Place</p></th>
        <th class="element-title"><p>start</p></th>
        <th class="element-title"><p>Line up</p></th>
        <th class="element-title"><p>Number of DJ</p></th>
        <th class="element-title"><p>Revenue figure</p></th>
        <th class="element-title"><p>Total charge DJ</p></th>
        <th class="element-title"><p>Charge communication</p></th>
        <th class="element-title"><p>Charge Others</p></th>
        <th class="element-title"><p>Benefits</p></th>
        <th class="element-title"><p class="scroll-x">Benefits rate (absolute indicator)</p></th>
        <th class="element-title"><p class="scroll-x">Return rate (relative indicator)</p></th>
        <th class="element-title"><p>Edit</p></th>
        <th class="element-title"><p>Show</p></th>
        <th class="element-title"><p>Delete</p></th>
      </tr>
  </thead>

  <tbody class="content">
    <%= render partial: 'event', collection: @events %>

  </tbody>
</table>

<div class="just-column">
  <div class="just-row">
    <p>Benefice total : </p><p class="calcul"><%= Event.total_benefits %> $ </p>
  </div>

  <p><br></p>

  <div class="just-row">
    <p>Benefice moyen : </p><p class="calcul"><%= Event.average_benefits%> $ </p>
  </div>

  <p><br></p>
<div class="end-block">

  <div class="new-link-event">
    <div class="hide-link">
      <%= link_to 'ADD NEW EVENT', new_event_path, id:'ajax-add-new-event', remote: true%>
    </div>
  </div>
</div>



</div>

app/views/events/new.html.erb
<div class="form-import-csv-events">
<p><br></p>
<p><br></p>
<p><br></p>
<p><br></p>
<p><br></p>
<p><br></p>

  <%= form_tag import_events_path, multipart: true, remote: true do%>
  <div class="just-row">
    <p>Add an Event : </p>
    <div id="submit-column">
      <div class="just-row"><p><%= file_field_tag :file %></p></div>
      <div class="just-row pink">
      <p class="save-button"><%= image_submit_tag("add.png", width:"35px") %></p>
      <p style="font-size:12px;">Ajouter le fichier CSV</p>
      </div>
    </div>
  </div>
  <% end %>

</div>

app/views/events/new.js.erb
$('.new-link-event').append("<%= j render 'form'%>");
$('.hide-link').hide(1800);

app/views/events/show.html.erb
<div class="event-show">

<div class="title-show-event">

<h1><%= @event.name %></h1><p class="return-button"><%= link_to image_tag('return.png'), events_path%></p></div>
 <div class="just-row2"><p>Club </p><p class="data"><%=@event.place%></p> </div>
 <div class="just-row2"><p>Line up </p><p class="data"><%= @event.line_up %></p></div>
 <div class="just-row2"><p>number of dj </p><p class="data"><%= @event.number_of_dj %></p></div>
 <div class="just-row2"><p>Description </p><p class="data"><%= @event.charge_others_description %></p></div>

 <% if @event.revenue_figure.nil? %>
 <%else%>
 <div class="just-row2"><p>C.A. </p><p class="data"><%= @event.revenue_figure %>$</p></div>
 <%end%>

 <% if @event.total_charge_dj.nil? %>
 <%else%>
 <div class="just-row2"><p>Charge DJ </p><p class="data"><%= @event.total_charge_dj %>$</p></div>
 <%end%>

 <% if @event.charge_communication.nil? %>
 <%else%>
 <div class="just-row2"><p>Charge comunication </p><p class="data"><%= @event.charge_communication %>$</p></div>
 <%end%>

 <% if @event.charge_others.nil? %>
 <%else%>
 <div class="just-row2"><p>Charge Others </p><p class="data"><%= @event.charge_others %>$</p></div>
 <%end%>

 <% if @event.benefits.nil? %>
 <%else%>
<div class="just-row2"><p>Benefits </p><p  class="calcul"> <%= @event.benefits %> $</p></div>
<%end%>

<% if @event.benefits.nil? %>
<%else%>
<div class="just-row2"><p>Benefits rate </p>
  <% if @event.positiv_benefits_rate %>
  <p class = "positiv"><%= @event.benefits_rate %>%</p>
  <% else %>
  <p class="negativ"><%= @event.benefits_rate %>%</p>
  <%end%></div>
  <%end%>

  <% if @event.return_rate.nil? %>
  <%else%>
<div class="just-row2"><p>Return rate </p>  <% if @event.positiv_return_rate %>
  <p class = "positiv"><%= @event.return_rate %>%</p>
  <% else %>
  <p class="negativ"><%= @event.return_rate %>%</p>
  <%end%></div>
  <%end%>


</div>